# 第一阶段：构建 React 应用
FROM node:latest as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build


FROM python:3.12-slim-buster
WORKDIR /translate-app
COPY --from=build-stage /app/build /translate-app/front-end/build
COPY requirements.txt requirements.txt
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && pip install -r requirements.txt
COPY . .
CMD ["bash", "deploy.sh"]