FROM node:latest as build-stage
WORKDIR /app
COPY front-end/package*.json /app
RUN npm install
COPY front-end .
RUN npm run build


FROM python:3.12.0-alpine3.18
WORKDIR /translate-app
COPY --from=build-stage /app/build /translate-app/front-end/build
COPY requirements.txt requirements.txt
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && pip install -r requirements.txt
COPY . .
CMD ["bash", "deploy.sh"]